//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDemoHHH
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// 基本属性类
    /// </summary>
    public partial class BasicAttr555
    {
        /// <summary>
        /// Id
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 事件名称
        /// </summary>
        public string AttrName { get; set; }

        /// <summary>
        /// 举办城市
        /// </summary>
        public string Holding_City { get; set; }

        /// <summary>
        /// 开始时间
        /// </summary>
        public string Start_Time { get; set; }

        /// <summary>
        /// 结束时间
        /// </summary>
        public string End_Time { get; set; }

        /// <summary>
        /// 是否是国际组织
        /// </summary>
        public Nullable<bool> Is_International { get; set; }

        /// <summary>
        /// 是否是国家组织
        /// </summary>
        public Nullable<bool> Is_c_Government { get; set; }

        /// <summary>
        /// 是否是省政府
        /// </summary>
        public Nullable<bool> Is_p_Government { get; set; }

        /// <summary>
        /// 是否是地方政府
        /// </summary>
        public Nullable<bool> Is_l_Government { get; set; }

        /// <summary>
        /// 是否是国内民间协会
        /// </summary>
        public Nullable<bool> Is_Homecivil_Association { get; set; }

        /// <summary>
        /// 是否是国际民间协会
        /// </summary>
        public Nullable<bool> Is_Intercivil_Association { get; set; }

        /// <summary>
        /// 是否是国内行业协会
        /// </summary>
        public Nullable<bool> Is_Hometrade_Association { get; set; }

        /// <summary>
        /// 是否是国际行业协会
        /// </summary>
        public Nullable<bool> Is_Intertrade_Association { get; set; }

        /// <summary>
        /// 是否影响儿童
        /// </summary>
        public Nullable<bool> Is_Influence_Children { get; set; }

        /// <summary>
        /// 是否影响青年
        /// </summary>
        public Nullable<bool> Is_Influence_Young { get; set; }

        /// <summary>
        /// 是否影响成年
        /// </summary>
        public Nullable<bool> Is_Influence_Adult { get; set; }

        /// <summary>
        /// 是否影响老年
        /// </summary>
        public Nullable<bool> Is_Influence_Old { get; set; }

        /// <summary>
        /// 是否有固定人群
        /// </summary>
        public Nullable<bool> Participant_Population { get; set; }

        /// <summary>
        /// 是否影响商务人群
        /// </summary>
        public Nullable<bool> Is_Influence_Business { get; set; }

        /// <summary>
        /// 是否影响社会大众
        /// </summary>
        public Nullable<bool> Is_Influence_Generalpublic { get; set; }

        /// <summary>
        /// 最大影响全球
        /// </summary>
        public Nullable<bool> Is_Influence_Worldwide { get; set; }

        /// <summary>
        /// 最大影响洲际
        /// </summary>
        public Nullable<bool> Is_Influence_Intercontinental { get; set; }

        /// <summary>
        /// 最大影响全国
        /// </summary>
        public Nullable<bool> Is_Influence_Wholecountry { get; set; }

        /// <summary>
        /// 最大影响全省
        /// </summary>
        public Nullable<bool> Is_Influence_Province { get; set; }

        /// <summary>
        /// 最大影响全市
        /// </summary>
        public Nullable<bool> Is_Influence_City { get; set; }

        /// <summary>
        /// 是否是展会
        /// </summary>
        public Nullable<bool> Is_Exhibition { get; set; }

        /// <summary>
        /// 是否是演唱会
        /// </summary>
        public Nullable<bool> Is_Concert { get; set; }

        /// <summary>
        /// 是否是体育赛事
        /// </summary>
        public Nullable<bool> Is_Sportevent { get; set; }

        /// <summary>
        /// 是否是会议
        /// </summary>
        public Nullable<bool> Is_Meeting { get; set; }

        /// <summary>
        /// 是否是地方性节假日
        /// </summary>
        public Nullable<bool> Is_Localholiday { get; set; }

        /// <summary>
        /// 事件热度
        /// </summary>
        public Nullable<int> Event_Fever { get; set; }

        /// <summary>
        /// 事件历史悠久度
        /// </summary>
        public Nullable<int> Event_History { get; set; }

        /// <summary>
        /// 事件一年内频率
        /// </summary>
        public Nullable<int> Freq { get; set; }
    }
}
