//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicAttr
    {
        public int Id { get; set; }
        public string AttrName { get; set; }
        public string Holding_City { get; set; }
        public string Start_Time { get; set; }
        public string End_Time { get; set; }
        public Nullable<bool> Is_International { get; set; }
        public Nullable<bool> Is_c_Government { get; set; }
        public Nullable<bool> Is_p_Government { get; set; }
        public Nullable<bool> Is_l_Government { get; set; }
        public Nullable<bool> Is_Homecivil_Association { get; set; }
        public Nullable<bool> Is_Intercivil_Association { get; set; }
        public Nullable<bool> Is_Hometrade_Association { get; set; }
        public Nullable<bool> Is_Intertrade_Association { get; set; }
        public Nullable<bool> Is_Influence_Children { get; set; }
        public Nullable<bool> Is_Influence_Young { get; set; }
        public Nullable<bool> Is_Influence_Adult { get; set; }
        public Nullable<bool> Is_Influence_Old { get; set; }
        public Nullable<bool> Participant_Population { get; set; }
        public Nullable<bool> Is_Influence_Business { get; set; }
        public Nullable<bool> Is_Influence_Generalpublic { get; set; }
        public Nullable<bool> Is_Influence_Worldwide { get; set; }
        public Nullable<bool> Is_Influence_Intercontinental { get; set; }
        public Nullable<bool> Is_Influence_Wholecountry { get; set; }
        public Nullable<bool> Is_Influence_Province { get; set; }
        public Nullable<bool> Is_Influence_City { get; set; }
        public Nullable<bool> Is_Exhibition { get; set; }
        public Nullable<bool> Is_Concert { get; set; }
        public Nullable<bool> Is_Sportevent { get; set; }
        public Nullable<bool> Is_Meeting { get; set; }
        public Nullable<bool> Is_Localholiday { get; set; }
        public Nullable<int> Event_Fever { get; set; }
        public Nullable<int> Event_History { get; set; }
        public Nullable<int> Freq { get; set; }
    }
}
