//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebRule
    {
        public int Id { get; set; }
        public string UrlName { get; set; }
        public string UrlWeb { get; set; }
        public string WebContentXpath { get; set; }
        public string Response { get; set; }
        public string RequestUrl { get; set; }
        public string WebName { get; set; }
        public string AttrContentXpath { get; set; }
        public string PageXpath { get; set; }
    }
}
